project:
  type: book
  output-dir: docs

book:
  title: "데이터 분석 전문가(ADP) 가이드"
  date: "2023. 5. 18."
  search: true
  site-url: https://juhyeonpark.com/adp-test-with-r/
  repo-url: https://github.com/jhyeonpark/adp-test-with-r/
  chapters:
    - index.qmd
    - intro.qmd
    - part: section_previous_tests.qmd
      chapters:
      - test_26.qmd
      - test_27.qmd
    - summary.qmd
    - references.qmd
  
toc-depth: 1
bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo, theme.scss, anari-custom.scss]
        dark: [cosmo, theme-dark.scss, anari-custom.scss]
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

